### ISSUE TITLE
No index error

### ISSUE THREAD

**Issue by dlackty** [adamyi/golinks#1]
Hello,
First of all, thanks for this nice tool!

After installation, I saw an error
```
NeedIndexError: no matching index found. The suggested index for this query is: - kind: Link properties: - name: owner_id
```

from the following lines:
https://github.com/adamyi/golinks/blob/9d4e648b5dac74041c9a0943109ae8bd63d6d8a6/appengine_main.py#L39

I'm not familiar with GAE & DataStore, but I guessed some sort of index or database settings are missing?

**Comment by adamyi** [comment]
Hi sorry for the delayed reply

I just set up a fresh copy and couldn't reproduce this issue using either Cloud Datastore or Cloud Firestore in Datastore mode.

How Cloud Datastore works is that for every query, it needs to have the corresponding pre-built index in place to work. But Cloud Datastore would automatically create indexes for single properties. So for simple queries like this, no index needs to be created manually.

My guess is that you are using Cloud Firestore in Native Mode for your GCP project, which does not support Cloud Datastore v1 API and is incompatible with GAE Python2.7 Runtime. According to https://github.com/GoogleCloudPlatform/datastore-ndb-python/issues/292, the NDB library would throw a NeedIndexError exception if used against Firestore.

Create a new GCP project and use Cloud Firestore in Datastore Mode and it should fix this. Otherwise, let me know if there are more issues.

FYI: https://cloud.google.com/datastore/docs/firestore-or-datastore

**Comment by dlackty** [comment]
@adamyi Thanks for your explanation and you're totally right. I'm using Firestore for my GCP project which causes the problem.
